#include "utils/FileManager.h"
#include <vector>

#include <iostream>

void HarbourUtils::FileManager::createNewDirectory(std::string dir)
{
	std::filesystem::create_directory(dir);
}

void HarbourUtils::FileManager::writeFile(std::string file, std::string data)
{
	std::ofstream stream(file);
	stream << data << std::endl;
	stream.close();
}

std::string HarbourUtils::FileManager::readFile(std::string file)
{
	std::vector<std::string> contents = {};

	std::ifstream stream(file);

	std::string result = "";
	for (int i = 0; i < contents.size(); i++) {
		result += contents.at(i);
	}
	return result;

}

nlohmann::json HarbourUtils::FileManager::readJSON(std::string file)
{
	//minimalistic function assisted by Brave Search Assist

	std::ifstream stream(file);
	nlohmann::json j = {};
	stream >> j;

	return j;
}


//WriteCallback generated by AI, based on https://gist.github.com/whoshuu/2dc858b8730079602044
//If anyone knows better cURL usage or documentation (especially for C++), it would be appreciated greatly
static size_t WriteCallback(void* contents, size_t size, size_t nmemb, std::string* s) {
    size_t totalSize = size * nmemb;
    s->append((char*)contents, totalSize);
    return totalSize;
}

int HarbourUtils::FileManager::makeCURLRequest(const char* url)
{
    CURL* curl = curl_easy_init();
    std::string response;

    if (curl) {
        // Set URL
        curl_easy_setopt(curl, CURLOPT_URL, url);

        // Set User-Agent (required by GitHub API)
        curl_easy_setopt(curl, CURLOPT_USERAGENT, "libcurl-example/1.0");

        // Set callback to capture response
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);

        // Perform request
        CURLcode res = curl_easy_perform(curl);

        if (res == CURLE_OK) {
            std::cout << "Response: " << response << std::endl;
        }
        else {
            std::cerr << "Request failed: " << curl_easy_strerror(res) << std::endl;
        }

        curl_easy_cleanup(curl);
    }

    return 0;
}
