#include "utils/FileManager.h"
#include <vector>
#include <filesystem>
#include <fstream>
#include <sstream>

#include <iostream>

void HarbourUtils::FileManager::createNewDirectory(std::string dir)
{
	std::filesystem::create_directory(dir);
}

void HarbourUtils::FileManager::writeFile(std::string file, std::string data)
{
	std::ofstream stream(file);
	stream << data << std::endl;
	stream.close();
}

std::string HarbourUtils::FileManager::readFile(std::string file)
{
	std::vector<std::string> contents = {};

	std::ifstream stream(file);

	std::string result = "";
	for (int i = 0; i < contents.size(); i++) {
		result += contents.at(i);
	}
	return result;

}

nlohmann::json HarbourUtils::FileManager::readJSON(std::string file)
{
	//minimalistic function assisted by Brave Search Assist

	std::ifstream stream(file);
	nlohmann::json j = {};
	stream >> j;

	return j;
}

void HarbourUtils::FileManager::constructLibraryFromJSON(std::vector<Harbour::GameCard>& output, std::string lib)
{
    auto res = this->readJSON(lib);

    if (res.size() == 0) return;

    for (size_t i = 0; i < res.size(); i++) {
        std::cout << res[i].at("name") << std::endl << res[i].at("version") << std::endl;
        output.emplace_back(res[i].at("name"), res[i].at("version"));
    }
}

//WriteCallback generated by AI, based on https://gist.github.com/whoshuu/2dc858b8730079602044
//If anyone knows better cURL usage or documentation (especially for C++), it would be appreciated greatly
static size_t WriteCallback(void* contents, size_t size, size_t nmemb, std::string* s) {
    size_t totalSize = size * nmemb;
    s->append((char*)contents, totalSize);
    return totalSize;
}

std::string HarbourUtils::FileManager::makeCURLRequest(const char* url)
{
    CURL* curl = curl_easy_init();
    std::string response;

    if (curl) {
        // Set URL
        curl_easy_setopt(curl, CURLOPT_URL, url);

        // Set User-Agent (required by GitHub API)
        curl_easy_setopt(curl, CURLOPT_USERAGENT, "libcurl-example/1.0");

        // Set callback to capture response
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);

        // Perform request
        CURLcode res = curl_easy_perform(curl);

        if (res == CURLE_OK) {
            //std::cout << "Response: " << response << std::endl;
        }
        else {
            std::cerr << "Request failed: " << curl_easy_strerror(res) << std::endl;
        }

        curl_easy_cleanup(curl);
    }

    return response;
}

void HarbourUtils::FileManager::checkLatestVersions()
{
    //Get/check install links for versions based on version
#if defined(_WIN32)
    auto latest = this->checkShipVersion();
    auto installed = this->readJSON("library/myGames.json");

    std::cout << "Latest: " << latest.dump(4) << std::endl;
    std::cout << "Installed: " << installed << std::endl;
    std::cout << installed.size() << std::endl;

#elif defined(__linux__)

#elif defined(__APPLE__)
#endif
}

void HarbourUtils::FileManager::startGame(std::string file)
{
#if defined(_WIN32)
	//Use CreateProcess or ShellExecute to start the selected game
#elif defined(__linux__)
	//Use posix_spawn or fork + exec to start the selected game
#elif defined(__APPLE__)
	//Implement similar to Linux for starting game, possibly merge the two
#endif
}

nlohmann::json HarbourUtils::FileManager::checkShipVersion()
{
    nlohmann::json ship = nlohmann::json::parse( makeCURLRequest("https://api.github.com/repos/HarbourMasters/Shipwright/releases/latest") );
    this->parseVersionString( ship.value("tag_name") );
    //this->parseVersionString( /*Something with the user's library*/);
    //std::cout << ship << std::endl;
    return ship;
}

nlohmann::json HarbourUtils::FileManager::check2ShipVersion()
{
    nlohmann::json ship2 = nlohmann::json::parse ( makeCURLRequest("https://api.github.com/repos/HarbourMasters/2Ship2Harkinian/releases/latest") );

    

    return ship2;
}

nlohmann::json HarbourUtils::FileManager::checkStarShipVersion()
{
    nlohmann::json starship = nlohmann::json::parse(makeCURLRequest("https://api.github.com/repos/HarbourMasters/2Ship2Harkinian/releases/latest"));
    return starship;
}

//Both ChatGPT and Github Copilot had the same idea for this function and wrote it
HarbourUtils::VersionInfo HarbourUtils::FileManager::parseVersionString(const std::string& versionStr)
{
    VersionInfo vi = {};
	std::stringstream ss(versionStr);
    std::string section;

	if (std::getline(ss, section, '.')) vi.major = std::stoi(section);
    if (std::getline(ss, section, '.')) vi.minor = std::stoi(section);
    if (std::getline(ss, section, '.')) vi.patch = std::stoi(section);

    return vi;
}

bool HarbourUtils::FileManager::versionOutdated(const VersionInfo& installed, const VersionInfo& latest)
{
    if (installed.major < latest.major) return true;
    if (installed.minor < latest.minor) return true;
    if (installed.patch < latest.patch) return true;

    return false;
}
