name: build-harbour-ports-linux

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Restore vcpkg Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg
            ${{ github.workspace }}/vcpkg_installed
            ${{ github.workspace }}/external/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Get other dependencies
        run: |
          sudo apt install -y autoconf autoconf-archive automake libtoolize

      - name: Run Build commands
        run: |
          chmod +x ./buildLinux-release.sh
          ./buildLinux-release.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: harbour-linux
          path: build/Release/
          if-no-files-found: error
